name: grocery
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  badges: ^3.1.2
  cached_network_image: ^3.4.1
  card_swiper: ^3.0.1
  cupertino_icons: ^1.0.8
  fancy_shimmer_image: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_staggered_grid_view: ^0.7.0
  get_it: ^7.7.0
  go_router: ^14.2.7
  iconly: ^1.0.1
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/cat/
    - assets/images/offres/
    - assets/images/landing/

# Custom configuration for flutter_assets
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/
  filename: appAssets.dart
